spring:
  application:
    name: fehmarnopen

  datasource:
    url: jdbc:sqlite:fehmarnopen.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: true
    show-sql: true
